apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "weather-app.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        {{- include "weather-app.labels" . | nindent 8 }}

    spec:
      nodeSelector:
        kubernetes.io/hostname: vkubelet
      tolerations:
        - key: "virtual-kubelet.io/provider"
          operator: "Exists"
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.service.port }}
          envFrom:
            - secretRef:
                name: aws-credentials
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            requests:
              cpu: 250m
