apiVersion: v1
kind: Secret
metadata:
  name: aws-secret1  # This is the name of the secret
  namespace: default  # Change this if using a different namespace
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.awsCredentials.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsCredentials.secretAccessKey | b64enc }}
  AWS_DEFAULT_REGION: {{ .Values.awsCredentials.region | b64enc }}
