apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vallamkondu/My-weather-app.git
    targetRevision: main
    path: charts/weather-app
    helm:
      values: |
        image:
          repository: "dikshit328/weather-app"
          tag: "1743784251"
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: false
      prune: true
