apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: weather-app-set
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/vallamkondu/My-weather-app.git
        revision: main
        directories:
          - path: charts/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/vallamkondu/My-weather-app.git
        targetRevision: main
        path: '{{path}}'
        helm:
          values: |
            image:
              repository: dikshit328/weather-app
              tag: "1743784251"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: false
          prune: true
