name: Build and deploy docker image in k8s
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set-image-tag.outputs.IMAGE_TAG }}  # Expose IMAGE_TAG to next job

    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set IMAGE_TAG
      id: set-image-tag
      run: |
        IMAGE_TAG=$(date +%s)
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Build and Push Docker Image
      run: |
        docker build \
          --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          --build-arg AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }} \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/weather-app:${{ env.IMAGE_TAG }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/weather-app:${{ env.IMAGE_TAG }}


  terraform_deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      AWS_DEFAULT_REGION: eu-north-1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Terraform plan
        working-directory: ./terraform
        run: |  
          terraform plan

      - name: Apply Terraform
        working-directory: ./terraform
        run: |
          terraform apply -auto-approve
        

  Deploy-Helm:
    needs: [build-and-push, terraform_deploy]
    runs-on: self-hosted  # Uses self-hosted runner
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Display IMAGE_TAG
        run: |
          echo "Deploying with IMAGE_TAG=${{ needs.build-and-push.outputs.IMAGE_TAG }}"

      - name: run unittest
        run: helm unittest charts/weather-app
        
      - name: Deploy Helm Chart
        
        run: |
          helm upgrade --install weather-app charts/weather-app `
            --set image.repository="${{ secrets.DOCKERHUB_USERNAME }}/weather-app" `
            --set image.tag="${{ needs.build-and-push.outputs.IMAGE_TAG }}"

      - name: Wait for pods to be ready
        run: |
          sleep 30
          kubectl get pods



